
def char(pixel_framebuf, s, x, y, color):
  if s == "1":
    pixel_framebuf.pixel(x+0,y+0, color=color)
    pixel_framebuf.pixel(x+0,y+1, color=color)
    pixel_framebuf.pixel(x+0,y+2, color=color)
    pixel_framebuf.pixel(x+0,y+3, color=color)
    pixel_framebuf.pixel(x+0,y+4, color=color)
    pixel_framebuf.pixel(x+0,y+5, color=color)
    pixel_framebuf.pixel(x+0,y+6, color=color)
  if s == "1a":
    pixel_framebuf.pixel(x+1,y+0, color=color)
    pixel_framebuf.pixel(x+0,y+1, color=color)
    pixel_framebuf.pixel(x+1,y+1, color=color)
    pixel_framebuf.pixel(x+1,y+2, color=color)
    pixel_framebuf.pixel(x+1,y+3, color=color)
    pixel_framebuf.pixel(x+1,y+4, color=color)
    pixel_framebuf.pixel(x+1,y+5, color=color)
    pixel_framebuf.pixel(x+0,y+6, color=color)
    pixel_framebuf.pixel(x+1,y+6, color=color)
    pixel_framebuf.pixel(x+2,y+6, color=color)
  if s == "2":
    pixel_framebuf.pixel(x+1,y+0, color=color)
    pixel_framebuf.pixel(x+2,y+0, color=color)
    pixel_framebuf.pixel(x+0,y+1, color=color)
    pixel_framebuf.pixel(x+3,y+1, color=color)
    pixel_framebuf.pixel(x+3,y+2, color=color)
    pixel_framebuf.pixel(x+1,y+3, color=color)
    pixel_framebuf.pixel(x+2,y+3, color=color)
    pixel_framebuf.pixel(x+0,y+4, color=color)
    pixel_framebuf.pixel(x+0,y+5, color=color)
    pixel_framebuf.pixel(x+0,y+6, color=color)
    pixel_framebuf.pixel(x+1,y+6, color=color)
    pixel_framebuf.pixel(x+2,y+6, color=color)
    pixel_framebuf.pixel(x+3,y+6, color=color)
  if s == "3":
    pixel_framebuf.pixel(x+0,y+0, color=color)
    pixel_framebuf.pixel(x+1,y+0, color=color)
    pixel_framebuf.pixel(x+2,y+0, color=color)
    pixel_framebuf.pixel(x+3,y+0, color=color)
    pixel_framebuf.pixel(x+3,y+1, color=color)
    pixel_framebuf.pixel(x+2,y+2, color=color)
    pixel_framebuf.pixel(x+1,y+3, color=color)
    pixel_framebuf.pixel(x+2,y+3, color=color)
    pixel_framebuf.pixel(x+3,y+4, color=color)
    pixel_framebuf.pixel(x+0,y+5, color=color)
    pixel_framebuf.pixel(x+3,y+5, color=color)
    pixel_framebuf.pixel(x+1,y+6, color=color)
    pixel_framebuf.pixel(x+2,y+6, color=color)
  if s == "4":
    pixel_framebuf.pixel(x+0,y+0, color=color)
    pixel_framebuf.pixel(x+2,y+0, color=color)
    pixel_framebuf.pixel(x+0,y+1, color=color)
    pixel_framebuf.pixel(x+2,y+1, color=color)
    pixel_framebuf.pixel(x+0,y+2, color=color)
    pixel_framebuf.pixel(x+2,y+2, color=color)
    pixel_framebuf.pixel(x+0,y+3, color=color)
    pixel_framebuf.pixel(x+1,y+3, color=color)
    pixel_framebuf.pixel(x+2,y+3, color=color)
    pixel_framebuf.pixel(x+3,y+3, color=color)
    pixel_framebuf.pixel(x+2,y+4, color=color)
    pixel_framebuf.pixel(x+2,y+5, color=color)
    pixel_framebuf.pixel(x+2,y+6, color=color)
  if s == "4a":
    pixel_framebuf.pixel(x+2,y+0, color=color)
    pixel_framebuf.pixel(x+1,y+1, color=color)
    pixel_framebuf.pixel(x+2,y+1, color=color)
    pixel_framebuf.pixel(x+0,y+2, color=color)
    pixel_framebuf.pixel(x+2,y+2, color=color)
    pixel_framebuf.pixel(x+0,y+3, color=color)
    pixel_framebuf.pixel(x+2,y+3, color=color)
    pixel_framebuf.pixel(x+0,y+4, color=color)
    pixel_framebuf.pixel(x+1,y+4, color=color)
    pixel_framebuf.pixel(x+2,y+4, color=color)
    pixel_framebuf.pixel(x+3,y+4, color=color)
    pixel_framebuf.pixel(x+2,y+5, color=color)
    pixel_framebuf.pixel(x+2,y+6, color=color)
  if s == "5":
    pixel_framebuf.pixel(x+0,y+0, color=color)
    pixel_framebuf.pixel(x+1,y+0, color=color)
    pixel_framebuf.pixel(x+2,y+0, color=color)
    pixel_framebuf.pixel(x+3,y+0, color=color)
    pixel_framebuf.pixel(x+0,y+1, color=color)
    pixel_framebuf.pixel(x+0,y+2, color=color)
    pixel_framebuf.pixel(x+1,y+2, color=color)
    pixel_framebuf.pixel(x+2,y+2, color=color)
    pixel_framebuf.pixel(x+3,y+3, color=color)
    pixel_framebuf.pixel(x+3,y+4, color=color)
    pixel_framebuf.pixel(x+0,y+5, color=color)
    pixel_framebuf.pixel(x+3,y+5, color=color)
    pixel_framebuf.pixel(x+1,y+6, color=color)
    pixel_framebuf.pixel(x+2,y+6, color=color)
  if s == "6":
    pixel_framebuf.pixel(x+2,y+0, color=color)
    pixel_framebuf.pixel(x+3,y+0, color=color)
    pixel_framebuf.pixel(x+1,y+1, color=color)
    pixel_framebuf.pixel(x+0,y+2, color=color)
    pixel_framebuf.pixel(x+0,y+3, color=color)
    pixel_framebuf.pixel(x+1,y+3, color=color)
    pixel_framebuf.pixel(x+2,y+3, color=color)
    pixel_framebuf.pixel(x+0,y+4, color=color)
    pixel_framebuf.pixel(x+3,y+4, color=color)
    pixel_framebuf.pixel(x+0,y+5, color=color)
    pixel_framebuf.pixel(x+3,y+5, color=color)
    pixel_framebuf.pixel(x+1,y+6, color=color)
    pixel_framebuf.pixel(x+2,y+6, color=color)
  if s == "7":
    pixel_framebuf.pixel(x+0,y+0, color=color)
    pixel_framebuf.pixel(x+1,y+0, color=color)
    pixel_framebuf.pixel(x+2,y+0, color=color)
    pixel_framebuf.pixel(x+3,y+0, color=color)
    pixel_framebuf.pixel(x+3,y+1, color=color)
    pixel_framebuf.pixel(x+3,y+2, color=color)
    pixel_framebuf.pixel(x+2,y+3, color=color)
    pixel_framebuf.pixel(x+1,y+4, color=color)
    pixel_framebuf.pixel(x+0,y+5, color=color)
    pixel_framebuf.pixel(x+0,y+6, color=color)
  if s == "8":
    pixel_framebuf.pixel(x+1,y+0, color=color)
    pixel_framebuf.pixel(x+2,y+0, color=color)
    pixel_framebuf.pixel(x+0,y+1, color=color)
    pixel_framebuf.pixel(x+3,y+1, color=color)
    pixel_framebuf.pixel(x+0,y+2, color=color)
    pixel_framebuf.pixel(x+3,y+2, color=color)
    pixel_framebuf.pixel(x+1,y+3, color=color)
    pixel_framebuf.pixel(x+2,y+3, color=color)
    pixel_framebuf.pixel(x+0,y+4, color=color)
    pixel_framebuf.pixel(x+3,y+4, color=color)
    pixel_framebuf.pixel(x+0,y+5, color=color)
    pixel_framebuf.pixel(x+3,y+5, color=color)
    pixel_framebuf.pixel(x+1,y+6, color=color)
    pixel_framebuf.pixel(x+2,y+6, color=color)
  if s == "9":
    pixel_framebuf.pixel(x+1,y+0, color=color)
    pixel_framebuf.pixel(x+2,y+0, color=color)
    pixel_framebuf.pixel(x+0,y+1, color=color)
    pixel_framebuf.pixel(x+3,y+1, color=color)
    pixel_framebuf.pixel(x+0,y+2, color=color)
    pixel_framebuf.pixel(x+3,y+2, color=color)
    pixel_framebuf.pixel(x+1,y+3, color=color)
    pixel_framebuf.pixel(x+2,y+3, color=color)
    pixel_framebuf.pixel(x+3,y+3, color=color)
    pixel_framebuf.pixel(x+3,y+4, color=color)
    pixel_framebuf.pixel(x+2,y+5, color=color)
    pixel_framebuf.pixel(x+0,y+6, color=color)
    pixel_framebuf.pixel(x+1,y+6, color=color)
  if s == "0":
    pixel_framebuf.pixel(x+1,y+0, color=color)
    pixel_framebuf.pixel(x+2,y+0, color=color)
    pixel_framebuf.pixel(x+0,y+1, color=color)
    pixel_framebuf.pixel(x+3,y+1, color=color)
    pixel_framebuf.pixel(x+0,y+2, color=color)
    pixel_framebuf.pixel(x+3,y+2, color=color)
    pixel_framebuf.pixel(x+0,y+3, color=color)
    pixel_framebuf.pixel(x+2,y+3, color=color)
    pixel_framebuf.pixel(x+3,y+3, color=color)
    pixel_framebuf.pixel(x+0,y+4, color=color)
    pixel_framebuf.pixel(x+1,y+4, color=color)
    pixel_framebuf.pixel(x+3,y+4, color=color)
    pixel_framebuf.pixel(x+0,y+5, color=color)
    pixel_framebuf.pixel(x+3,y+5, color=color)
    pixel_framebuf.pixel(x+1,y+6, color=color)
    pixel_framebuf.pixel(x+2,y+6, color=color)
  if s == ":":
    pixel_framebuf.pixel(x+0,y+2, color=color)
    pixel_framebuf.pixel(x+0,y+4, color=color)

